/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'myicons';

  static const IconData home = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData apartment = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData pencil = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData magic_wand = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData lighter = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData sun = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData cloud = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData cloud_upload = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData cloud_download = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData cloud_sync = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData cloud_check = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData lock = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData cog = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData trash = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData star = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData flag = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData paperclip = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData inbox = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData eye = IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData file_empty = IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData enter = IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData exit = IconData(0xe820, fontFamily: _kFontFam);
  static const IconData license = IconData(0xe822, fontFamily: _kFontFam);
  static const IconData film_play = IconData(0xe824, fontFamily: _kFontFam);
  static const IconData camera_video = IconData(0xe825, fontFamily: _kFontFam);
  static const IconData camera = IconData(0xe826, fontFamily: _kFontFam);
  static const IconData picture = IconData(0xe827, fontFamily: _kFontFam);
  static const IconData book = IconData(0xe828, fontFamily: _kFontFam);
  static const IconData bookmark = IconData(0xe829, fontFamily: _kFontFam);
  static const IconData user = IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData users = IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData tag = IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData phone_handset = IconData(0xe830, fontFamily: _kFontFam);
  static const IconData pushpin = IconData(0xe832, fontFamily: _kFontFam);
  static const IconData map_marker = IconData(0xe833, fontFamily: _kFontFam);
  static const IconData location = IconData(0xe835, fontFamily: _kFontFam);
  static const IconData calendar_full = IconData(0xe836, fontFamily: _kFontFam);
  static const IconData power_swtich = IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData lnr_bubble = IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData heart_pulse = IconData(0xe840, fontFamily: _kFontFam);
  static const IconData construction = IconData(0xe841, fontFamily: _kFontFam);
  static const IconData pie_chart = IconData(0xe842, fontFamily: _kFontFam);
  static const IconData chart_bars = IconData(0xe843, fontFamily: _kFontFam);
  static const IconData rocket = IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData bicycle = IconData(0xe850, fontFamily: _kFontFam);
  static const IconData wheelchair = IconData(0xe851, fontFamily: _kFontFam);
  static const IconData earth = IconData(0xe853, fontFamily: _kFontFam);
  static const IconData smile = IconData(0xe854, fontFamily: _kFontFam);
  static const IconData sad = IconData(0xe855, fontFamily: _kFontFam);
  static const IconData neutral = IconData(0xe856, fontFamily: _kFontFam);
  static const IconData mustache = IconData(0xe857, fontFamily: _kFontFam);
  static const IconData alarm = IconData(0xe858, fontFamily: _kFontFam);
  static const IconData bullhorn = IconData(0xe859, fontFamily: _kFontFam);
  static const IconData hourglass = IconData(0xe85f, fontFamily: _kFontFam);
  static const IconData clock = IconData(0xe864, fontFamily: _kFontFam);
  static const IconData download = IconData(0xe865, fontFamily: _kFontFam);
  static const IconData upload = IconData(0xe866, fontFamily: _kFontFam);
  static const IconData enter_down = IconData(0xe867, fontFamily: _kFontFam);
  static const IconData exit_up = IconData(0xe868, fontFamily: _kFontFam);
  static const IconData code = IconData(0xe86a, fontFamily: _kFontFam);
  static const IconData thumbs_up = IconData(0xe86d, fontFamily: _kFontFam);
  static const IconData thumbs_down = IconData(0xe86e, fontFamily: _kFontFam);
  static const IconData magnifier = IconData(0xe86f, fontFamily: _kFontFam);
  static const IconData menu = IconData(0xe871, fontFamily: _kFontFam);
  static const IconData list = IconData(0xe872, fontFamily: _kFontFam);
  static const IconData chevron_up = IconData(0xe873, fontFamily: _kFontFam);
  static const IconData chevron_down = IconData(0xe874, fontFamily: _kFontFam);
  static const IconData chevron_left = IconData(0xe875, fontFamily: _kFontFam);
  static const IconData chevron_right = IconData(0xe876, fontFamily: _kFontFam);
  static const IconData arrow_up = IconData(0xe877, fontFamily: _kFontFam);
  static const IconData arrow_down = IconData(0xe878, fontFamily: _kFontFam);
  static const IconData arrow_left = IconData(0xe879, fontFamily: _kFontFam);
  static const IconData arrow_right = IconData(0xe87a, fontFamily: _kFontFam);
  static const IconData move = IconData(0xe87b, fontFamily: _kFontFam);
  static const IconData warning = IconData(0xe87c, fontFamily: _kFontFam);
  static const IconData question_circle = IconData(0xe87d, fontFamily: _kFontFam);
  static const IconData menu_circle = IconData(0xe87e, fontFamily: _kFontFam);
  static const IconData checkmark_cicle = IconData(0xe87f, fontFamily: _kFontFam);
  static const IconData cross_circle = IconData(0xe880, fontFamily: _kFontFam);
  static const IconData plus_circle = IconData(0xe881, fontFamily: _kFontFam);
  static const IconData circle_minus = IconData(0xe882, fontFamily: _kFontFam);
  static const IconData arrow_up_circle = IconData(0xe883, fontFamily: _kFontFam);
  static const IconData arrow_down_circle = IconData(0xe884, fontFamily: _kFontFam);
  static const IconData arrow_left_circle = IconData(0xe885, fontFamily: _kFontFam);
  static const IconData arrow_right_circle = IconData(0xe886, fontFamily: _kFontFam);
  static const IconData chevron_up_circle = IconData(0xe887, fontFamily: _kFontFam);
  static const IconData chevron_down_circle = IconData(0xe888, fontFamily: _kFontFam);
  static const IconData chevron_left_circle = IconData(0xe889, fontFamily: _kFontFam);
  static const IconData chevron_right_circle = IconData(0xe88a, fontFamily: _kFontFam);
  static const IconData frame_expand = IconData(0xe88c, fontFamily: _kFontFam);
  static const IconData frame_contract = IconData(0xe88d, fontFamily: _kFontFam);
  static const IconData hand = IconData(0xe8a5, fontFamily: _kFontFam);
  static const IconData pointer_up = IconData(0xe8a6, fontFamily: _kFontFam);
  static const IconData pointer_right = IconData(0xe8a7, fontFamily: _kFontFam);
  static const IconData pointer_down = IconData(0xe8a8, fontFamily: _kFontFam);
  static const IconData pointer_left = IconData(0xe8a9, fontFamily: _kFontFam);
}
