/// Flutter icons Soshal
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Soshal
///      fonts:
///       - asset: fonts/Soshal.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Soshal {
  Soshal._();

  static const _kFontFam = 'Soshal';

  static const IconData facebook__2_ = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData twitter__1_ = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData github__1_ = IconData(0xe802, fontFamily: _kFontFam);
}
